+define+S50
+define+VERBOSE
+incdir+./RTL/core
./testbench_top.sv
./clock_gen.sv
./interface.sv
./environment/estimulo1.sv
./environment/estimulo2.sv
./environment/estimulo3.sv
./environment/scoreboard.sv
./environment/driver.sv
./environment/driver_2.sv
./environment/driver_3.sv
./environment/monitor.sv
./environment/environment.sv
./environment/environment2.sv
./test_program.sv
./duv/memory_controller.sv
./RTL/lib/async_fifo.v
./RTL/model/IS42VM16400K.V
./RTL/model/mt48lc2m32b2.v
./RTL/model/mt48lc8m8a2.v
./RTL/wb2sdrc/wb2sdrc.v
./RTL/core/sdrc_core.v
./RTL/core/sdrc_bank_ctl.v
./RTL/core/sdrc_bank_fsm.v
./RTL/core/sdrc_bs_convert.v
./RTL/core/sdrc_req_gen.v
./RTL/core/sdrc_xfr_ctl.v 
./assertions_interface.sv
./aserciones_entrega2.sv